version: '2.1'

services:

  web:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile_dev
    command: npm start
    container_name: angular-starter-template-dev
    image: angular-starter-template/dev
    volumes:
      - ./src:/home/node/angular-starter-template/src
    networks:
      - dev-network
    ports:
      - '5555:5555'

networks:
  dev-network:
    driver: bridge
